### ISSUE TITLE
Step-by-step instructions

### ISSUE THREAD

**Issue by JazzfanRS** [GHbasicuser/RB2RS-Database-Converter#1]
Step by step instructions would be nice, for people that have never used Power Shell scripts. Pictures not necessary.

I installed MariaDB, after some problems (Learning how to use it) I managed to load the RBI sql.

USE `backup_de1_2022-09-27.sql`;
/* SQL Error (1049): Unknown database 'backup_de1_2022-09-27.sql' */
/* Loading file "D:\warne\Downloads\backup_de1_2022-09-27.sql" (18.8 MiB) into query tab `#1` ... */

**Comment by GHbasicuser** [comment]
Hi

This script runs like any other PowerShell script... just take note of these points :

-  Usage (**must be configured before use**) : ./RB2RS-converter.ps1
-  This script should be used with a local MariaDB server & 7zip.
-  Recommended PowerShell version : 7 (and above)

Here is the configuration part :
`$RB_source = "https://backups.radio-browser.info/latest.sql.gz"`
`$destination = "D:\temp" # Local directory to generate tmp files and ".rsd" `

`#Specify the path to the 7Zip compression-decompression tool. (7z.exe)`
`$7zprogram = "C:\Program Files\7-Zip\7z.exe"`

`#Local database access settings (MariaDB)`
`$RBHost = "localhost"`
`$RBPort = "3306"`
`$RBUser = "**********"`
`$RBPassword = "**********"`

`#This temporary RBBase will be modified and deleted. (if $tempDB = $true)`
`$RBBase = "_RBDB"`

`#If you want to leave this RBBase on the server, set $tempDB = $false`
`$tempDB = $true `

Which part should be developed ?  🧐

**Comment by JazzfanRS** [comment]
I've never used PS. Do I cut and paste the script at the command prompt?

**Comment by JazzfanRS** [comment]
ACtually, nevermind. I will just keep using the conversion from the website. I was hoping to DL the RBI and create a NP++ script to create my own .rsd. Too much work, with a working conversion already.

**Comment by GHbasicuser** [comment]
I can't replace a tutorial, but here are the essentials :
- once the powersehll window is open, go to the folder containing the script, eg: `cd d:\powershell_script\`
- then to launch the script (once you have configured it), you must write its name preceded by "./" then validate, eg: `./RB2RS-converter.ps1`

**Comment by JazzfanRS** [comment]
I am leaving the project as I intended it to be a contact point for the lost volunteers. Even before a successful conversion, it is apparent that they would not be returning, and true RS enthusiasts that continued to use RS now have a working conversion. Terribly messy compared to what we've been used to, but working nonetheless. I am ready to be done with this. 

It's been an interesting experience. I've learned a bit about programming and db management. I will continue to use the conversions a long as they are available. I will leave information on website contact page in the chance our own editable database is established and I am wanted to manage or assist with this.

Currently looking at what to do with the github. I no longer desire to continue participation. But for now I will leave it as is.

**Comment by GHbasicuser** [comment]
> ACtually, nevermind. I will just keep using the conversion from the website. I was hoping to DL the RBI and create a NP++ script to create my own .rsd. Too much work, with a working conversion already.

Yes, if you want to modify an existing ".rsd" (text) file with a text editor, you might as well take it from francois-neosurf's server, because this powershell script is already done to modify the RBi database, so you need to know how to "program" in powershell and how to use mariaDB queries. 😐

**Comment by JazzfanRS** [comment]
Okay thanks I will do that. I think you might want to just delete this issue. AS it really isn't one. CErtainly all these messages. Continue doing a great job with the conversion scripts!

**Comment by GHbasicuser** [comment]
> I am leaving the project as I intended it to be a contact point for the lost volunteers. Even before a successful conversion, it is apparent that they would not be returning, and true RS enthusiasts that continued to use RS now have a working conversion. Terribly messy compared to what we've been used to, but working nonetheless. I am ready to be done with this.
> 
> It's been an interesting experience. I've learned a bit about programming and db management. I will continue to use the conversions a long as they are available. I will leave information on website contact page in the chance our own editable database is established and I am wanted to manage or assist with this.
> 
> Currently looking at what to do with the github. I no longer desire to continue participation. But for now I will leave it as is.

It seems to me that creating a forum on the radiosure.fr site could make you change your mind (and mine 😉), but you would have to ask François (he is the one who has the information required to create a database linked to a forum: url/logon/mdp),... but maybe he's more reluctant there than I think...the latest messages regarding duplicates and HLS streams (although reported several times in the last few months) didn't make him react either. 🤔

**Comment by GHbasicuser** [comment]
> I think you might want to just delete this issue. AS it really isn't one. CErtainly all these messages.

Ok. 😅
> Continue doing a great job with the conversion scripts!

Thank you !🙂
